// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list_artists.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/core/catalog/infra/InMemoryArtistRepository.ts
var InMemoryArtistRepository = class {
  items = /* @__PURE__ */ new Map();
  async findAll() {
    return Array.from(this.items.values());
  }
  async findById(id) {
    return this.items.get(id) ?? null;
  }
  async save(artist) {
    this.items.set(artist.id.toString(), artist);
  }
};

// src/core/catalog/infra/InMemoryReleaseRepository.ts
var InMemoryReleaseRepository = class {
  items = /* @__PURE__ */ new Map();
  async findAll() {
    return Array.from(this.items.values());
  }
  async findById(id) {
    return this.items.get(id) ?? null;
  }
  async findByArtistId(artistId) {
    return Array.from(this.items.values()).filter((r) => r.artistId === artistId);
  }
  async save(release) {
    this.items.set(release.id.toString(), release);
  }
};

// src/core/distribution/infra/InMemoryDeliveryRepository.ts
var InMemoryDeliveryRepository = class {
  items = /* @__PURE__ */ new Map();
  async findAll() {
    return Array.from(this.items.values());
  }
  async findByReleaseId(releaseId) {
    return Array.from(this.items.values()).filter((d) => d.releaseId === releaseId);
  }
  async save(d) {
    this.items.set(d.id.toString(), d);
  }
};

// src/core/royalties/infra/InMemoryRoyaltyRepository.ts
var InMemoryRoyaltyRepository = class {
  items = [];
  async findAll() {
    return [...this.items];
  }
  async findByPeriod(period) {
    return this.items.filter((l) => l.period === period);
  }
  async saveBatch(lines) {
    this.items.push(...lines);
  }
};

// src/core/wallet/infra/InMemoryWalletRepository.ts
var InMemoryWalletRepository = class {
  items = /* @__PURE__ */ new Map();
  async findByArtistId(artistId) {
    return Array.from(this.items.values()).find((w) => w.artistId === artistId) ?? null;
  }
  async save(w) {
    this.items.set(w.id.toString(), w);
  }
};
var InMemoryWithdrawalRepository = class {
  items = /* @__PURE__ */ new Map();
  async findAll() {
    return Array.from(this.items.values());
  }
  async findByArtistId(artistId) {
    return Array.from(this.items.values()).filter((w) => w.artistId === artistId);
  }
  async save(w) {
    this.items.set(w.id.toString(), w);
  }
};

// src/core/smartlinks/infra/InMemorySmartLinkRepository.ts
var InMemorySmartLinkRepository = class {
  items = /* @__PURE__ */ new Map();
  async findAll() {
    return Array.from(this.items.values());
  }
  async findByReleaseId(id) {
    return Array.from(this.items.values()).filter((s) => s.releaseId === id);
  }
  async save(s) {
    this.items.set(s.id.toString(), s);
  }
};

// src/core/fraud/infra/InMemoryFraudRepository.ts
var InMemoryFraudRepository = class {
  items = /* @__PURE__ */ new Map();
  async findAll() {
    return Array.from(this.items.values());
  }
  async save(a) {
    this.items.set(a.id.toString(), a);
  }
};

// src/core/shared/domain/UniqueId.ts
var UniqueId = class {
  value;
  constructor(value) {
    this.value = value ?? crypto.randomUUID();
  }
  toString() {
    return this.value;
  }
  equals(other) {
    return this.value === other.value;
  }
};

// src/core/shared/domain/Entity.ts
var Entity = class {
  _id;
  props;
  constructor(props, id) {
    this._id = id ?? new UniqueId();
    this.props = props;
  }
  get id() {
    return this._id;
  }
  equals(other) {
    if (!other) return false;
    return this._id.equals(other._id);
  }
};

// src/core/catalog/domain/Artist.ts
var Artist = class _Artist extends Entity {
  static create(props, id) {
    return new _Artist(props, id);
  }
  get name() {
    return this.props.name;
  }
  get avatar() {
    return this.props.avatar;
  }
  get monthlyListeners() {
    return this.props.monthlyListeners;
  }
  get bio() {
    return this.props.bio;
  }
};

// src/core/catalog/domain/Release.ts
var Release = class _Release extends Entity {
  static create(props, id) {
    if (!props.title?.trim()) throw new Error("Release: t\xEDtulo obrigat\xF3rio");
    if (!props.tracks?.length) throw new Error("Release: precisa de ao menos 1 faixa");
    return new _Release(props, id);
  }
  submitForReview() {
    if (this.props.status !== "draft") throw new Error("Apenas rascunhos podem ser enviados");
    this.props.status = "review";
  }
  approve() {
    this.props.status = "scheduled";
  }
  publish() {
    this.props.status = "live";
  }
  reject() {
    this.props.status = "rejected";
  }
  get title() {
    return this.props.title;
  }
  get artistId() {
    return this.props.artistId;
  }
  get artistName() {
    return this.props.artistName;
  }
  get cover() {
    return this.props.cover;
  }
  get type() {
    return this.props.type;
  }
  get releaseDate() {
    return this.props.releaseDate;
  }
  get status() {
    return this.props.status;
  }
  get genre() {
    return this.props.genre;
  }
  get explicit() {
    return this.props.explicit;
  }
  get tracks() {
    return this.props.tracks;
  }
  get preSaveLink() {
    return this.props.preSaveLink;
  }
  get upc() {
    return this.props.upc;
  }
};

// src/core/catalog/domain/Track.ts
var Track = class _Track extends Entity {
  static create(props, id) {
    return new _Track(props, id);
  }
  get title() {
    return this.props.title;
  }
  get duration() {
    return this.props.duration;
  }
  get isrc() {
    return this.props.isrc;
  }
  get explicit() {
    return this.props.explicit;
  }
};

// src/core/catalog/application/CatalogMapper.ts
var CatalogMapper = class _CatalogMapper {
  static artistToDTO(a) {
    return {
      id: a.id.toString(),
      name: a.name,
      avatar: a.avatar,
      monthlyListeners: a.monthlyListeners,
      bio: a.bio
    };
  }
  static artistToDomain(dto) {
    return Artist.create(
      {
        name: dto.name,
        avatar: dto.avatar,
        monthlyListeners: dto.monthlyListeners,
        bio: dto.bio
      },
      new UniqueId(dto.id)
    );
  }
  static trackToDTO(t) {
    return {
      id: t.id.toString(),
      title: t.title,
      duration: t.duration,
      isrc: t.isrc,
      explicit: t.explicit
    };
  }
  static trackToDomain(dto) {
    return Track.create(
      { title: dto.title, duration: dto.duration, isrc: dto.isrc, explicit: dto.explicit },
      new UniqueId(dto.id)
    );
  }
  static releaseToDTO(r) {
    return {
      id: r.id.toString(),
      title: r.title,
      artistId: r.artistId,
      artistName: r.artistName,
      cover: r.cover,
      type: r.type,
      releaseDate: r.releaseDate,
      status: r.status,
      genre: r.genre,
      explicit: r.explicit,
      tracks: r.tracks.map(_CatalogMapper.trackToDTO),
      preSaveLink: r.preSaveLink,
      upc: r.upc
    };
  }
  static releaseToDomain(dto) {
    return Release.create(
      {
        title: dto.title,
        artistId: dto.artistId,
        artistName: dto.artistName,
        cover: dto.cover,
        type: dto.type,
        releaseDate: dto.releaseDate,
        status: dto.status,
        genre: dto.genre,
        explicit: dto.explicit,
        tracks: dto.tracks.map(_CatalogMapper.trackToDomain),
        preSaveLink: dto.preSaveLink,
        upc: dto.upc
      },
      new UniqueId(dto.id)
    );
  }
};

// src/core/catalog/application/ListArtistsUseCase.ts
var ListArtistsUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    const artists = await this.repo.findAll();
    return artists.map(CatalogMapper.artistToDTO);
  }
};

// src/core/catalog/application/ListReleasesUseCase.ts
var ListReleasesUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    const releases = await this.repo.findAll();
    return releases.map(CatalogMapper.releaseToDTO);
  }
};

// src/core/distribution/domain/Delivery.ts
var Delivery = class _Delivery extends Entity {
  static create(props, id) {
    return new _Delivery(props, id);
  }
  markDelivered(when) {
    this.props.status = "delivered";
    this.props.liveAt = when;
  }
  markFailed(reason) {
    this.props.status = "failed";
    this.props.errorMessage = reason;
  }
  get releaseId() {
    return this.props.releaseId;
  }
  get dsp() {
    return this.props.dsp;
  }
  get status() {
    return this.props.status;
  }
  get submittedAt() {
    return this.props.submittedAt;
  }
  get liveAt() {
    return this.props.liveAt;
  }
  get errorMessage() {
    return this.props.errorMessage;
  }
};

// src/core/distribution/application/DistributionMapper.ts
var DistributionMapper = class {
  static toDTO(d) {
    return {
      id: d.id.toString(),
      releaseId: d.releaseId,
      dsp: d.dsp,
      status: d.status,
      submittedAt: d.submittedAt,
      liveAt: d.liveAt,
      errorMessage: d.errorMessage
    };
  }
  static toDomain(dto) {
    return Delivery.create(
      {
        releaseId: dto.releaseId,
        dsp: dto.dsp,
        status: dto.status,
        submittedAt: dto.submittedAt,
        liveAt: dto.liveAt,
        errorMessage: dto.errorMessage
      },
      new UniqueId(dto.id)
    );
  }
};

// src/core/distribution/application/ListDeliveriesUseCase.ts
var ListDeliveriesUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    const items = await this.repo.findAll();
    return items.map(DistributionMapper.toDTO);
  }
};

// src/core/shared/domain/Money.ts
var Money = class _Money {
  constructor(amount, currency = "BRL") {
    this.amount = amount;
    this.currency = currency;
    if (Number.isNaN(amount)) throw new Error("Money: amount inv\xE1lido");
  }
  amount;
  currency;
  add(other) {
    this.assertSameCurrency(other);
    return new _Money(this.amount + other.amount, this.currency);
  }
  subtract(other) {
    this.assertSameCurrency(other);
    return new _Money(this.amount - other.amount, this.currency);
  }
  multiply(factor) {
    return new _Money(this.amount * factor, this.currency);
  }
  format(locale = "pt-BR") {
    return new Intl.NumberFormat(locale, {
      style: "currency",
      currency: this.currency
    }).format(this.amount);
  }
  assertSameCurrency(other) {
    if (this.currency !== other.currency)
      throw new Error(`Money: moedas diferentes ${this.currency} vs ${other.currency}`);
  }
};

// src/core/royalties/domain/RoyaltyLine.ts
var RoyaltyLine = class _RoyaltyLine extends Entity {
  static create(props, id) {
    if (props.streams < 0) throw new Error("RoyaltyLine: streams negativo");
    return new _RoyaltyLine(props, id);
  }
  get trackId() {
    return this.props.trackId;
  }
  get trackTitle() {
    return this.props.trackTitle;
  }
  get artistId() {
    return this.props.artistId;
  }
  get dsp() {
    return this.props.dsp;
  }
  get country() {
    return this.props.country;
  }
  get streams() {
    return this.props.streams;
  }
  get gross() {
    return this.props.gross;
  }
  get net() {
    return this.props.net;
  }
  get period() {
    return this.props.period;
  }
};

// src/core/royalties/application/RoyaltyMapper.ts
var RoyaltyMapper = class {
  static toDTO(l) {
    return {
      id: l.id.toString(),
      trackId: l.trackId,
      trackTitle: l.trackTitle,
      artistId: l.artistId,
      dsp: l.dsp,
      country: l.country,
      streams: l.streams,
      grossAmount: l.gross.amount,
      netAmount: l.net.amount,
      currency: l.gross.currency,
      period: l.period
    };
  }
  static toDomain(dto) {
    return RoyaltyLine.create(
      {
        trackId: dto.trackId,
        trackTitle: dto.trackTitle,
        artistId: dto.artistId,
        dsp: dto.dsp,
        country: dto.country,
        streams: dto.streams,
        gross: new Money(dto.grossAmount, dto.currency),
        net: new Money(dto.netAmount, dto.currency),
        period: dto.period
      },
      new UniqueId(dto.id)
    );
  }
};

// src/core/royalties/application/ListRoyaltiesUseCase.ts
var ListRoyaltiesUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    const items = await this.repo.findAll();
    return items.map(RoyaltyMapper.toDTO);
  }
};

// src/core/royalties/application/ImportRoyaltyReportUseCase.ts
var ImportRoyaltyReportUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute(input) {
    const fee = input.feeRate ?? 0.15;
    const currency = input.currency ?? "BRL";
    const lines = input.rows.map(
      (r) => RoyaltyLine.create({
        trackId: r.trackId,
        trackTitle: r.trackTitle,
        artistId: r.artistId,
        dsp: input.dsp,
        country: r.country,
        streams: r.streams,
        gross: new Money(r.gross, currency),
        net: new Money(r.gross * (1 - fee), currency),
        period: input.period
      })
    );
    await this.repo.saveBatch(lines);
    const totalGross = lines.reduce((s, l) => s + l.gross.amount, 0);
    const totalNet = lines.reduce((s, l) => s + l.net.amount, 0);
    return { imported: lines.length, totalGross, totalNet, currency };
  }
};

// src/core/wallet/domain/Wallet.ts
var Wallet = class _Wallet extends Entity {
  static create(props, id) {
    return new _Wallet(props, id);
  }
  canWithdraw(amount) {
    return this.props.available.amount >= amount.amount;
  }
  debit(amount) {
    if (!this.canWithdraw(amount)) throw new Error("Saldo insuficiente");
    this.props.available = this.props.available.subtract(amount);
  }
  credit(amount) {
    this.props.available = this.props.available.add(amount);
    this.props.lifetimeEarnings = this.props.lifetimeEarnings.add(amount);
  }
  get artistId() {
    return this.props.artistId;
  }
  get available() {
    return this.props.available;
  }
  get pending() {
    return this.props.pending;
  }
  get lifetimeEarnings() {
    return this.props.lifetimeEarnings;
  }
};

// src/core/wallet/domain/Withdrawal.ts
var Withdrawal = class _Withdrawal extends Entity {
  static create(props, id) {
    if (props.amount.amount <= 0) throw new Error("Withdrawal: valor deve ser positivo");
    return new _Withdrawal(props, id);
  }
  approve() {
    this.props.status = "processing";
  }
  complete(when) {
    this.props.status = "completed";
    this.props.completedAt = when;
  }
  fail() {
    this.props.status = "failed";
  }
  get artistId() {
    return this.props.artistId;
  }
  get artistName() {
    return this.props.artistName;
  }
  get amount() {
    return this.props.amount;
  }
  get method() {
    return this.props.method;
  }
  get status() {
    return this.props.status;
  }
  get requestedAt() {
    return this.props.requestedAt;
  }
  get completedAt() {
    return this.props.completedAt;
  }
};

// src/core/wallet/application/WalletMapper.ts
var WalletMapper = class {
  static walletToDTO(w) {
    return {
      id: w.id.toString(),
      artistId: w.artistId,
      available: w.available.amount,
      pending: w.pending.amount,
      lifetimeEarnings: w.lifetimeEarnings.amount,
      currency: w.available.currency
    };
  }
  static walletToDomain(dto) {
    return Wallet.create(
      {
        artistId: dto.artistId,
        available: new Money(dto.available, dto.currency),
        pending: new Money(dto.pending, dto.currency),
        lifetimeEarnings: new Money(dto.lifetimeEarnings, dto.currency)
      },
      new UniqueId(dto.id)
    );
  }
  static withdrawalToDTO(w) {
    return {
      id: w.id.toString(),
      artistId: w.artistId,
      artistName: w.artistName,
      amount: w.amount.amount,
      currency: w.amount.currency,
      method: w.method,
      status: w.status,
      requestedAt: w.requestedAt,
      completedAt: w.completedAt
    };
  }
  static withdrawalToDomain(dto) {
    return Withdrawal.create(
      {
        artistId: dto.artistId,
        artistName: dto.artistName,
        amount: new Money(dto.amount, dto.currency),
        method: dto.method,
        status: dto.status,
        requestedAt: dto.requestedAt,
        completedAt: dto.completedAt
      },
      new UniqueId(dto.id)
    );
  }
};

// src/core/wallet/application/GetWalletUseCase.ts
var GetWalletUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute(artistId) {
    const w = await this.repo.findByArtistId(artistId);
    return w ? WalletMapper.walletToDTO(w) : null;
  }
};
var ListWithdrawalsUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    const items = await this.repo.findAll();
    return items.map(WalletMapper.withdrawalToDTO);
  }
};

// src/core/wallet/application/RequestWithdrawalUseCase.ts
var RequestWithdrawalUseCase = class {
  constructor(walletRepo, withdrawalRepo) {
    this.walletRepo = walletRepo;
    this.withdrawalRepo = withdrawalRepo;
  }
  walletRepo;
  withdrawalRepo;
  async execute(input) {
    const wallet = await this.walletRepo.findByArtistId(input.artistId);
    if (!wallet) throw new Error("Wallet n\xE3o encontrada");
    const amount = new Money(input.amount, input.currency);
    wallet.debit(amount);
    await this.walletRepo.save(wallet);
    const withdrawal = Withdrawal.create({
      artistId: input.artistId,
      artistName: input.artistName,
      amount,
      method: input.method,
      status: "pending",
      requestedAt: (/* @__PURE__ */ new Date()).toISOString()
    });
    await this.withdrawalRepo.save(withdrawal);
    return WalletMapper.withdrawalToDTO(withdrawal);
  }
};

// src/core/smartlinks/domain/SmartLink.ts
var SmartLink = class _SmartLink extends Entity {
  static create(props, id) {
    if (!props.slug) throw new Error("SmartLink: slug obrigat\xF3rio");
    return new _SmartLink(props, id);
  }
  registerVisit() {
    this.props.visits = this.props.visits + 1;
  }
  registerConversion() {
    this.props.conversions = this.props.conversions + 1;
  }
  get url() {
    return `https://lnk.music/${this.props.slug}`;
  }
  get releaseId() {
    return this.props.releaseId;
  }
  get slug() {
    return this.props.slug;
  }
  get title() {
    return this.props.title;
  }
  get artwork() {
    return this.props.artwork;
  }
  get destinations() {
    return this.props.destinations;
  }
  get visits() {
    return this.props.visits;
  }
  get conversions() {
    return this.props.conversions;
  }
  get createdAt() {
    return this.props.createdAt;
  }
};

// src/core/smartlinks/application/SmartLinkMapper.ts
var SmartLinkMapper = class {
  static toDTO(s) {
    const rate = s.visits === 0 ? 0 : s.conversions / s.visits * 100;
    return {
      id: s.id.toString(),
      releaseId: s.releaseId,
      slug: s.slug,
      title: s.title,
      artwork: s.artwork,
      url: s.url,
      destinations: s.destinations,
      visits: s.visits,
      conversions: s.conversions,
      conversionRate: Number(rate.toFixed(2)),
      createdAt: s.createdAt
    };
  }
  static toDomain(dto) {
    return SmartLink.create(
      {
        releaseId: dto.releaseId,
        slug: dto.slug,
        title: dto.title,
        artwork: dto.artwork,
        destinations: dto.destinations,
        visits: dto.visits,
        conversions: dto.conversions,
        createdAt: dto.createdAt
      },
      new UniqueId(dto.id)
    );
  }
};

// src/core/smartlinks/application/ListSmartLinksUseCase.ts
var ListSmartLinksUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    return (await this.repo.findAll()).map(SmartLinkMapper.toDTO);
  }
};

// src/core/fraud/domain/FraudAlert.ts
var FraudAlert = class _FraudAlert extends Entity {
  static create(props, id) {
    return new _FraudAlert(props, id);
  }
  confirm() {
    this.props.status = "confirmed";
  }
  dismiss() {
    this.props.status = "dismissed";
  }
  investigate() {
    this.props.status = "investigating";
  }
  get trackId() {
    return this.props.trackId;
  }
  get trackTitle() {
    return this.props.trackTitle;
  }
  get artistName() {
    return this.props.artistName;
  }
  get dsp() {
    return this.props.dsp;
  }
  get detectedAt() {
    return this.props.detectedAt;
  }
  get reason() {
    return this.props.reason;
  }
  get suspiciousStreams() {
    return this.props.suspiciousStreams;
  }
  get severity() {
    return this.props.severity;
  }
  get status() {
    return this.props.status;
  }
};

// src/core/fraud/application/FraudMapper.ts
var FraudMapper = class {
  static toDTO(a) {
    return {
      id: a.id.toString(),
      trackId: a.trackId,
      trackTitle: a.trackTitle,
      artistName: a.artistName,
      dsp: a.dsp,
      detectedAt: a.detectedAt,
      reason: a.reason,
      suspiciousStreams: a.suspiciousStreams,
      severity: a.severity,
      status: a.status
    };
  }
  static toDomain(dto) {
    return FraudAlert.create(
      {
        trackId: dto.trackId,
        trackTitle: dto.trackTitle,
        artistName: dto.artistName,
        dsp: dto.dsp,
        detectedAt: dto.detectedAt,
        reason: dto.reason,
        suspiciousStreams: dto.suspiciousStreams,
        severity: dto.severity,
        status: dto.status
      },
      new UniqueId(dto.id)
    );
  }
};

// src/core/fraud/application/ListFraudAlertsUseCase.ts
var ListFraudAlertsUseCase = class {
  constructor(repo) {
    this.repo = repo;
  }
  repo;
  async execute() {
    return (await this.repo.findAll()).map(FraudMapper.toDTO);
  }
};

// src/core/seed.ts
var seedArtists = [
  Artist.create({
    name: "Luna Nova",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    monthlyListeners: 125e3,
    bio: "Pop alternativo brasileiro"
  }, new UniqueId("artist-1")),
  Artist.create({
    name: "The Midnight Echo",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    monthlyListeners: 89e3
  }, new UniqueId("artist-2")),
  Artist.create({
    name: "Velocity",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    monthlyListeners: 234e3
  }, new UniqueId("artist-3"))
];
var seedReleases = [
  Release.create({
    title: "Neon Dreams",
    artistId: "artist-1",
    artistName: "Luna Nova",
    cover: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=300&h=300&fit=crop",
    type: "single",
    releaseDate: "2024-03-15",
    status: "live",
    genre: "Pop",
    explicit: false,
    upc: "0123456789012",
    tracks: [
      Track.create({ title: "Neon Dreams", duration: "3:45", isrc: "USRC12345678", explicit: false }, new UniqueId("track-1"))
    ]
  }, new UniqueId("release-1")),
  Release.create({
    title: "Midnight Sessions",
    artistId: "artist-2",
    artistName: "The Midnight Echo",
    cover: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop",
    type: "ep",
    releaseDate: "2024-04-01",
    status: "scheduled",
    genre: "Electronic",
    explicit: true,
    tracks: [
      Track.create({ title: "Shadow Dance", duration: "4:12", isrc: "USRC12345679", explicit: false }, new UniqueId("track-2")),
      Track.create({ title: "Electric Pulse", duration: "3:58", isrc: "USRC12345680", explicit: true }, new UniqueId("track-3"))
    ]
  }, new UniqueId("release-2")),
  Release.create({
    title: "Velocity",
    artistId: "artist-3",
    artistName: "Velocity",
    cover: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop",
    type: "album",
    releaseDate: "2024-05-20",
    status: "review",
    genre: "Hip-Hop",
    explicit: true,
    tracks: [
      Track.create({ title: "Fast Lane", duration: "3:15", isrc: "USRC12345683", explicit: true }, new UniqueId("track-6")),
      Track.create({ title: "No Brakes", duration: "2:58", isrc: "USRC12345684", explicit: true }, new UniqueId("track-7"))
    ]
  }, new UniqueId("release-3"))
];
var seedDeliveries = [
  Delivery.create({ releaseId: "release-1", dsp: "Spotify", status: "delivered", submittedAt: "2024-03-10", liveAt: "2024-03-15" }),
  Delivery.create({ releaseId: "release-1", dsp: "Apple Music", status: "delivered", submittedAt: "2024-03-10", liveAt: "2024-03-15" }),
  Delivery.create({ releaseId: "release-1", dsp: "YouTube Music", status: "delivered", submittedAt: "2024-03-10", liveAt: "2024-03-16" }),
  Delivery.create({ releaseId: "release-2", dsp: "Spotify", status: "delivering", submittedAt: "2024-03-25" }),
  Delivery.create({ releaseId: "release-2", dsp: "Deezer", status: "queued", submittedAt: "2024-03-25" }),
  Delivery.create({ releaseId: "release-3", dsp: "TikTok", status: "failed", submittedAt: "2024-04-01", errorMessage: "Metadados inv\xE1lidos" })
];
var seedRoyalties = [
  RoyaltyLine.create({ trackId: "track-1", trackTitle: "Neon Dreams", artistId: "artist-1", dsp: "Spotify", country: "BR", streams: 45230, gross: new Money(180.92), net: new Money(144.74), period: "2024-02" }),
  RoyaltyLine.create({ trackId: "track-1", trackTitle: "Neon Dreams", artistId: "artist-1", dsp: "Apple Music", country: "US", streams: 23450, gross: new Money(234.5), net: new Money(187.6), period: "2024-02" }),
  RoyaltyLine.create({ trackId: "track-2", trackTitle: "Shadow Dance", artistId: "artist-2", dsp: "Spotify", country: "PT", streams: 67800, gross: new Money(271.2), net: new Money(216.96), period: "2024-02" }),
  RoyaltyLine.create({ trackId: "track-6", trackTitle: "Fast Lane", artistId: "artist-3", dsp: "TikTok", country: "BR", streams: 89e4, gross: new Money(445), net: new Money(356), period: "2024-02" })
];
var seedWallets = [
  Wallet.create({ artistId: "artist-1", available: new Money(3847.5), pending: new Money(1250), lifetimeEarnings: new Money(48230.1) }),
  Wallet.create({ artistId: "artist-2", available: new Money(1209.85), pending: new Money(540), lifetimeEarnings: new Money(15670.5) }),
  Wallet.create({ artistId: "artist-3", available: new Money(8932.4), pending: new Money(3120), lifetimeEarnings: new Money(102450.9) })
];
var seedWithdrawals = [
  Withdrawal.create({ artistId: "artist-1", artistName: "Luna Nova", amount: new Money(1250), method: "pix", status: "completed", requestedAt: "2024-02-15", completedAt: "2024-02-15" }),
  Withdrawal.create({ artistId: "artist-3", artistName: "Velocity", amount: new Money(2340), method: "paypal", status: "processing", requestedAt: "2024-03-01" }),
  Withdrawal.create({ artistId: "artist-1", artistName: "Luna Nova", amount: new Money(567.8), method: "pix", status: "pending", requestedAt: "2024-03-15" })
];
var seedSmartLinks = [
  SmartLink.create({
    releaseId: "release-1",
    slug: "neon-dreams",
    title: "Neon Dreams",
    artwork: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=300&h=300&fit=crop",
    destinations: [
      { dsp: "Spotify", url: "https://open.spotify.com/track/x" },
      { dsp: "Apple Music", url: "https://music.apple.com/x" },
      { dsp: "YouTube Music", url: "https://music.youtube.com/x" }
    ],
    visits: 12450,
    conversions: 4320,
    createdAt: "2024-03-10"
  }),
  SmartLink.create({
    releaseId: "release-2",
    slug: "midnight-sessions",
    title: "Midnight Sessions EP",
    artwork: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop",
    destinations: [
      { dsp: "Spotify", url: "https://open.spotify.com/album/y" },
      { dsp: "Deezer", url: "https://deezer.com/y" }
    ],
    visits: 3210,
    conversions: 890,
    createdAt: "2024-03-25"
  })
];
var seedFraudAlerts = [
  FraudAlert.create({
    trackId: "track-6",
    trackTitle: "Fast Lane",
    artistName: "Velocity",
    dsp: "Spotify",
    detectedAt: "2024-03-20T10:00:00",
    reason: "Pico de streams de bots em 1 cluster IP",
    suspiciousStreams: 18420,
    severity: "high",
    status: "investigating"
  }),
  FraudAlert.create({
    trackId: "track-2",
    trackTitle: "Shadow Dance",
    artistName: "The Midnight Echo",
    dsp: "TikTok",
    detectedAt: "2024-03-22T14:00:00",
    reason: "Padr\xE3o repetitivo de 30s seguido por skip",
    suspiciousStreams: 5210,
    severity: "medium",
    status: "open"
  }),
  FraudAlert.create({
    trackId: "track-1",
    trackTitle: "Neon Dreams",
    artistName: "Luna Nova",
    dsp: "Spotify",
    detectedAt: "2024-03-25T08:00:00",
    reason: "Streams an\xF4malos vindos de pa\xEDs sem audi\xEAncia",
    suspiciousStreams: 980,
    severity: "low",
    status: "dismissed"
  })
];

// src/core/container.ts
function buildContainer() {
  const artistRepo = new InMemoryArtistRepository();
  const releaseRepo = new InMemoryReleaseRepository();
  const deliveryRepo = new InMemoryDeliveryRepository();
  const royaltyRepo = new InMemoryRoyaltyRepository();
  const walletRepo = new InMemoryWalletRepository();
  const withdrawalRepo = new InMemoryWithdrawalRepository();
  const smartLinkRepo = new InMemorySmartLinkRepository();
  const fraudRepo = new InMemoryFraudRepository();
  seedArtists.forEach((a) => artistRepo.save(a));
  seedReleases.forEach((r) => releaseRepo.save(r));
  seedDeliveries.forEach((d) => deliveryRepo.save(d));
  royaltyRepo.saveBatch(seedRoyalties);
  seedWallets.forEach((w) => walletRepo.save(w));
  seedWithdrawals.forEach((w) => withdrawalRepo.save(w));
  seedSmartLinks.forEach((s) => smartLinkRepo.save(s));
  seedFraudAlerts.forEach((a) => fraudRepo.save(a));
  return {
    repos: { artistRepo, releaseRepo, deliveryRepo, royaltyRepo, walletRepo, withdrawalRepo, smartLinkRepo, fraudRepo },
    useCases: {
      listArtists: new ListArtistsUseCase(artistRepo),
      listReleases: new ListReleasesUseCase(releaseRepo),
      listDeliveries: new ListDeliveriesUseCase(deliveryRepo),
      listRoyalties: new ListRoyaltiesUseCase(royaltyRepo),
      importRoyalties: new ImportRoyaltyReportUseCase(royaltyRepo),
      getWallet: new GetWalletUseCase(walletRepo),
      listWithdrawals: new ListWithdrawalsUseCase(withdrawalRepo),
      requestWithdrawal: new RequestWithdrawalUseCase(walletRepo, withdrawalRepo),
      listSmartLinks: new ListSmartLinksUseCase(smartLinkRepo),
      listFraudAlerts: new ListFraudAlertsUseCase(fraudRepo)
    }
  };
}
var container = buildContainer();

// src/lib/mcp/tools/list_artists.ts
var list_artists_default = defineTool({
  name: "list_artists",
  title: "Listar artistas",
  description: "Lista os artistas do cat\xE1logo de demonstra\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await container.useCases.listArtists.execute();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/list_releases.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_releases_default = defineTool2({
  name: "list_releases",
  title: "Listar lan\xE7amentos",
  description: "Lista os lan\xE7amentos (singles, EPs, \xE1lbuns) do cat\xE1logo de demonstra\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await container.useCases.listReleases.execute();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/list_deliveries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_deliveries_default = defineTool3({
  name: "list_deliveries",
  title: "Listar entregas",
  description: "Lista o status de entrega dos lan\xE7amentos para as lojas digitais.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await container.useCases.listDeliveries.execute();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/list_royalties.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_royalties_default = defineTool4({
  name: "list_royalties",
  title: "Listar royalties",
  description: "Lista as linhas de royalties importadas dos relat\xF3rios das lojas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await container.useCases.listRoyalties.execute();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/list_smart_links.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_smart_links_default = defineTool5({
  name: "list_smart_links",
  title: "Listar smart links",
  description: "Lista os smart links de divulga\xE7\xE3o e suas m\xE9tricas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await container.useCases.listSmartLinks.execute();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/list_fraud_alerts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_fraud_alerts_default = defineTool6({
  name: "list_fraud_alerts",
  title: "Listar alertas de fraude",
  description: "Lista os alertas de streams artificiais detectados.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await container.useCases.listFraudAlerts.execute();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/get_wallet.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";
var get_wallet_default = defineTool7({
  name: "get_wallet",
  title: "Ver carteira do artista",
  description: "Mostra o saldo da carteira de um artista pelo ID (ex.: artist-1).",
  inputSchema: { artistId: z.string().min(1).describe("ID do artista, ex.: artist-1") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ artistId }) => {
    const data = await container.useCases.getWallet.execute(artistId);
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "remix-of-harmony-hub",
  title: "Remix of Harmony Hub",
  version: "0.1.0",
  instructions: "Ferramentas somente leitura da plataforma de distribui\xE7\xE3o musical (dados de demonstra\xE7\xE3o): artistas, lan\xE7amentos, entregas, royalties, smart links, alertas de fraude e carteira.",
  tools: [list_artists_default, list_releases_default, list_deliveries_default, list_royalties_default, list_smart_links_default, list_fraud_alerts_default, get_wallet_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
